// Builds the static website for Vercel (or any static host) into dist/.
//   HDD_SERVER_URL=https://your-server.onrender.com node scripts/build-web.mjs
//
// Copies public/ and shared/ into dist/, and writes dist/config.js so the page knows
// where the multiplayer server is. Uses only Node's built-in modules (no install needed).

import { cp, rm, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "dist");
const server = (process.env.HDD_SERVER_URL || "").trim().replace(/\/+$/, "");

if (server && !/^https?:\/\//i.test(server)) {
  console.error(`HDD_SERVER_URL must start with https:// (got "${server}")`);
  process.exit(1);
}

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });
await cp(path.join(ROOT, "public"), OUT, { recursive: true });
await cp(path.join(ROOT, "shared"), path.join(OUT, "shared"), { recursive: true });
await writeFile(path.join(OUT, "config.js"),
  `// Generated by scripts/build-web.mjs from HDD_SERVER_URL.\nwindow.HDD_CONFIG = { server: ${JSON.stringify(server)} };\n`);

console.log(`Built dist/ ${server ? `(multiplayer server: ${server})` : "(no HDD_SERVER_URL set: solo works, multiplayer will look for a server at this site's own address)"}`);
